# Generated by Django 5.0.6 on 2024-06-20 15:53

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=7, max_length=10, prefix='Aca', primary_key=True, serialize=False)),
                ('academic_year_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='Cour', primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credit_hours', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='Enro', primary_key=True, serialize=False, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('retake', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='Sec', primary_key=True, serialize=False, unique=True)),
                ('section_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='Sem', primary_key=True, serialize=False, unique=True)),
                ('semester_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='SemesterYear',
            fields=[
                ('semester_year_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='SemY', primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Semester Year',
                'verbose_name_plural': 'Semester Years',
            },
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('teacher_course_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='Teac', primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=7, max_length=11, prefix='year', primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSemesterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_semester_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='CourS', unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_semester_availabilities', to='academics.course')),
            ],
            options={
                'verbose_name': 'Course Semester Availability',
                'verbose_name_plural': 'Course Semester Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='Dep', primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ManyToManyField(to='academics.course')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
