# Generated by Django 5.0.6 on 2024-06-20 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Department', to='userauth.teacher'),
        ),
        migrations.AddField(
            model_name='coursesemesteravailability',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseSemesterAvailability', to='academics.department'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.coursesemesteravailability'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='userauth.student'),
        ),
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.department'),
        ),
        migrations.AddField(
            model_name='semesteryear',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_years', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='semesteryear',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='coursesemesteravailability',
            name='semester_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_semester_availabilities', to='academics.semesteryear'),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='course_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='academics.coursesemesteravailability'),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='academics.section'),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='userauth.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course_semester')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('section_id', 'section_name', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='semesteryear',
            unique_together={('semester', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesemesteravailability',
            unique_together={('course', 'semester_year', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together={('course_semester', 'section')},
        ),
    ]
