# Generated by Django 5.0.6 on 2024-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='academic_Semester',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('winter', 'Winter')], max_length=10, null=True),
        ),
    ]
