# Generated by Django 5.0.6 on 2024-06-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='choice',
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='selected_choice',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='choices/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_1_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='choices/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_2_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='choices/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_3_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_3_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='choices/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_4_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice_4_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='QuizChoice',
        ),
    ]
