# Generated by Django 5.0.6 on 2024-06-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_quizanswer_choice_quizanswer_selected_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='due_date',
            new_name='quiz_starting_date_and_time',
        ),
    ]
