# Generated by Django 5.0.6 on 2024-06-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_rename_due_date_quiz_quiz_starting_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
