# Generated by Django 5.0.6 on 2024-06-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_quiz_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit',
        ),
    ]
