# Generated by Django 5.0.6 on 2024-06-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_remove_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
